#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
echo "Execute 'deploy' script"

MANAGE="python ${OPENSHIFT_REPO_DIR}manage.py"
SYNC_DB="$MANAGE syncdb --migrate --noinput"
COLLECTSTATIC="$MANAGE collectstatic --noinput"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/postgresql92/root/usr/lib64/

echo "Copying settings_local..."
cp "${OPENSHIFT_REPO_DIR}venelin/settings_openshift.py" "${OPENSHIFT_REPO_DIR}settings_local.py"

echo "Activate enviroment"
source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo "Executing '$SYNC_DB'"
$SYNC_DB

echo "Executing '$COLLECTSTATIC'"
$COLLECTSTATIC
