name: venko-django-site

secrets:
  google-credentials:
    file: ./.google-credentials.json

volumes:
  data:

services:
  web:
    image: ghcr.io/vstoykov/venko-django-site:latest
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./Dockerfile
          action: rebuild
        - path: ./uv.lock
          action: rebuild
        - path: ./uwsgi.ini
          target: /app/uwsgi.ini
          action: sync+restart
        - path: ./runserver
          target: /app/runserver
          action: sync+restart
        - path: ./venelin/settings/local.py
          action: restart
        - path: ./venelin
          target: /app/venelin
          ignore:
            - "**/static/**"
            - "./venelin/settings/local.py"
          action: sync+restart
          initial_sync: true
        - path: ./venelin
          target: /app/venelin
          include:
            - "**/static/**"
          action: sync+exec
          initial_sync: true
          exec:
            command: python manage.py collectstatic --noinput
    cpu_count: 2
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512M
        reservations:
          cpus: "0.01"
          memory: 250M
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    ports:
      - "127.0.0.1:8000:8000/tcp"
    volumes:
      - data:/var/www
      - ./venelin/settings/local.py:/app/venelin/settings/local.py:ro,z
    secrets:
      - source: google-credentials
        target: /run/secrets/google/credentials.json
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google/credentials.json

  test:
    image: ghcr.io/vstoykov/venko-django-site:latest
    container_name: ${COMPOSE_PROJECT_NAME}-test
    command: python manage.py test -v3
    environment:
      - DJANGO_ENV=dev
    profiles:
      - test

