---
apiVersion: v1
kind: Secret
metadata:
  name: venko-django-site-secret-environment
data:
  DJANGO_SECRET_KEY: base64-encoded-secret-key
  GOOGLE_OAUTH2_KEY: base64-encoded-google-oauth2-key
  GOOGLE_OAUTH2_SECRET: base64-encoded-google-oauth2-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: venko-django-site-google-app-credentials
data:
  credentials.json: base64-encoded-google-application-credentials-json
  