#!/bin/bash
########################################################
#
#             Django site 
#   Startup script for Django fcgi server.
#
########################################################

# Tune needed settings.

# If nesesery change the user that run the server
OWNER="venko" 

INTERPRETER="/usr/bin/python"

MAXSPARE=3

# =======================================================
# Setting Project dir and Project name
# from this scripts directory
# =======================================================
OLD_PWD=$PWD
cd `dirname $0`
PROJDIR=$PWD
cd $OLD_PWD

MANAGE="$PROJDIR/manage.py"

PROJNAME=`basename $PROJDIR`
PIDFILE="$PROJDIR/$PROJNAME.pid"
SOCKET="$PROJDIR/fcgi.sock"


# ===========================================
#  End of configuration. Begin real script
# ===========================================

case $1 in

    stop)
      echo "Stopping ${PROJNAME}..."
      
      if [ -f $PIDFILE ]; then
          kill `cat -- $PIDFILE`
          rm -f -- $PIDFILE
      fi

      sleep 1

      if [ -S $SOCKET ]; then
          rm -f $SOCKET
      fi
    ;;



    start)
      echo "Starting ${PROJNAME}..." 
      
      COMMAND="$INTERPRETER \"$MANAGE\" runfcgi socket=\"$SOCKET\" pidfile=\"$PIDFILE\" workdir=\"$PROJDIR\" maxspare=$MAXSPARE"
      
      if [ $OWNER = $(whoami) ]; then
        sh -c "$COMMAND"
      else
        su $OWNER -c "$COMMAND"
      fi

      if [ -S $SOCKET ]; then
       chmod 666 $SOCKET
      fi
    ;;
    
    restart)
      $0 stop
      sleep 2
      $0 start
    ;;

    *)
      echo Bad usage.
    ;;

esac

cd $OLD_PWD

exit
