#!/bin/bash
########################################################
#
#             Django site 
#   Startup script for Django fcgi server.
#
########################################################

# Tune needed settings.

# If nesesery change the user that run the server
OWNER="venko" 

MIN_SPARE=1
MAX_SPARE=1   # Maximum spares for this project
MAX_CHILDREN=4

MANAGE="manage.py"   # Script that manage project
INTERPRETER="python"   # MANAGE interpreter


# =======================================================
# Setting Project dir and Project name
# from this scripts directory
# =======================================================
OLD_PWD=$PWD
cd `dirname $0`
PROJDIR=$PWD
cd $OLD_PWD

PROJNAME=`basename $PROJDIR`
PIDFILE="$PROJDIR/$PROJNAME.pid"
SOCKET="$PROJDIR/fcgi.sock"


# ===========================================
#  End of configuration. Begin real script
# ===========================================

case $1 in

    stop)
      echo "Stopping ${PROJNAME}..."
      
      if [ -f $PIDFILE ]; then
          kill `cat -- $PIDFILE`
          rm -f -- $PIDFILE
      fi

      sleep 1

      if [ -S $SOCKET ]; then
          rm -f $SOCKET
      fi
    ;;



    start)
      echo "Starting ${PROJNAME}..." 
      PARAMETERS="pidfile='$PIDFILE' minspare=$MIN_SPARE maxspare=$MAX_SPARE maxchildren=$MAX_CHILDREN"
      COMMAND="$INTERPRETER '$PROJDIR/$MANAGE' runfcgi socket='$SOCKET' $PARAMETERS "
      #echo $COMMAND
      
      if [ $OWNER = $(whoami) ]; then
        sh -c "$COMMAND"
      else
        su $OWNER -c "$COMMAND"
      fi

      if [ -S $SOCKET ]; then
       chmod 666 $SOCKET
      fi
    ;;
    
    restart)
      $0 stop
      sleep 1
      $0 start
    ;;

    *)
      echo Bad usage.
    ;;

esac

#cd $OLD_PWD

exit
