#!/bin/bash
#
# Django site        Startup script for Django fcgi server.

# Tune needed settings.

# If nesesery change the user that run the server
export OWNER="venko" 

OLD_PWD=$PWD
cd `dirname $0`

export PROJDIR=$PWD
export PIDFILE="$PROJDIR/$PROJNAME.pid"
export SOCKET="$PROJDIR/fcgi.sock"


case $1 in

    stop)

      if [ -f $PIDFILE ]; then
          kill `cat -- $PIDFILE`
          rm -f -- $PIDFILE
      fi

      sleep 1

      if [ -S $SOCKET ]; then
          rm -f $SOCKET
      fi
    ;;



    start|restart)

      $0 stop
      sleep 1
      
      echo "Starting server at home dir $PROJDIR" 
      if [ $OWNER = $(whoami) ]; then
        cd $PROJDIR
        /usr/bin/python manage.py runfcgi socket=$SOCKET pidfile=$PIDFILE
      else
        su $OWNER -c '
          cd $PROJDIR
          /usr/bin/python manage.py runfcgi socket=$SOCKET pidfile=$PIDFILE
        '
      fi

      if [ -S $SOCKET ]; then
       chmod 666 $SOCKET
      fi
    ;;

    *)
      echo Bad usage.
    ;;

esac

cd $OLD_PWD

exit
