#!/usr/bin/env bash

IP_ADDRESS=$(hostname -I | awk '{print $1}')
PORT=${PORT:-8000}
APP_DIR=$(realpath $(dirname $0))

exec uwsgi --master --ini=${APP_DIR}/uwsgi.ini --http=127.0.0.1:${PORT} --http=${IP_ADDRESS}:${PORT} --uid=www-data --gid=www-data --env=HOME=${APP_DIR}
