[tox]
envlist =
    py314-dj{61,60,52}
    py313-dj52
    py314-djmaster

[testenv]
commands = python -m pytest
deps =
    pytest-django>=4.11.1
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    dj61: Django>=6.1,<6.2
    djmaster: git+https://github.com/django/django.git#egg=Django

[pytest]
DJANGO_SETTINGS_MODULE = venelin.settings.test
python_files = tests.py test.py test_*.py

[flake8]
max-line-length = 120
exclude = tests/*
