import os
from .production import *  # NOQA

DEBUG = os.getenv("DEBUG") in ("true", "True", "1")
SUPPORT_HTTPS = os.getenv('SUPPORT_HTTPS', 'True') in ('true', 'True', '1')

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = SUPPORT_HTTPS
SESSION_COOKIE_SECURE = SUPPORT_HTTPS
CSRF_COOKIE_SECURE = SUPPORT_HTTPS
URLIZE_ASSUME_HTTPS = SUPPORT_HTTPS
SECURE_HSTS_SECONDS = 60 * 24 * 7 if SUPPORT_HTTPS else None

