name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version: [2.2, "3.0", 3.1, 3.2]
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      DJANGO_VERSION: ${{ matrix.django-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Run Tests for Python ${{ matrix.python-version }} and Django ${{ matrix.django-version }}
      run: |
        tox -e "py${PYTHON_VERSION/\./}-dj${DJANGO_VERSION/\./}"
